"""update-orders

Revision ID: 91812a47a14e
Revises: 5ec7ec9f3547
Create Date: 2021-03-14 23:22:47.581306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91812a47a14e'
down_revision = '5ec7ec9f3547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('inProgress', sa.Boolean(), nullable=False))
    op.drop_column('orders', 'donation_amount')
    op.drop_column('orders', 'amount_paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('amount_paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('donation_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('orders', 'inProgress')
    # ### end Alembic commands ###
