"""updated charities model to allow nullable addresses

Revision ID: 80d563955841
Revises: b3e218811b61
Create Date: 2021-03-15 03:51:35.257530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80d563955841'
down_revision = 'b3e218811b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charities', 'address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('charities', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('charities', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('charities', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('charities', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('charities', 'zip',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charities', 'zip',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('charities', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('charities', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('charities', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('charities', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('charities', 'address',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
