"""order_items_count

Revision ID: b3e218811b61
Revises: 91812a47a14e
Create Date: 2021-03-15 02:45:57.668199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e218811b61'
down_revision = '91812a47a14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('item_count', sa.Integer(), nullable=True))
    op.alter_column('order_items', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_items', 'item_count')
    # ### end Alembic commands ###
