"""order_items-model

Revision ID: e8fa6f531eb6
Revises: 80d563955841
Create Date: 2021-03-19 16:33:23.790899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fa6f531eb6'
down_revision = '80d563955841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('order_items', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('order_items', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('order_items', 'item_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('item_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('order_items', 'id')
    op.drop_column('order_items', 'date_modified')
    op.drop_column('order_items', 'date_created')
    # ### end Alembic commands ###
